"""add sharpe and stats columns

Revision ID: 13d84041888d
Revises: d75fe3d0fa2a
Create Date: 2026-01-09 13:20:49.938389

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13d84041888d'
down_revision: Union[str, Sequence[str], None] = 'd75fe3d0fa2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('features_daily', sa.Column('skew_21', sa.Float(), nullable=True))
    op.add_column('features_daily', sa.Column('skew_63', sa.Float(), nullable=True))
    op.add_column('features_daily', sa.Column('zscore_21', sa.Float(), nullable=True))
    op.add_column('features_daily', sa.Column('zscore_63', sa.Float(), nullable=True))
    op.add_column('features_daily', sa.Column('rs_normalized', sa.Float(), nullable=True))
    op.add_column('features_daily', sa.Column('sharpe_21', sa.Float(), nullable=True))
    op.add_column('features_daily', sa.Column('sharpe_63', sa.Float(), nullable=True))
    op.add_column('features_daily', sa.Column('sharpe_126', sa.Float(), nullable=True))
    op.add_column('features_daily', sa.Column('sharpe_252', sa.Float(), nullable=True))
    op.drop_column('features_daily', 'zscore_60')
    op.drop_column('features_daily', 'skew_60')
    op.drop_column('features_daily', 'skew_20')
    op.drop_column('features_daily', 'zscore_20')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('features_daily', sa.Column('zscore_20', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('features_daily', sa.Column('skew_20', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('features_daily', sa.Column('skew_60', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('features_daily', sa.Column('zscore_60', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('features_daily', 'sharpe_252')
    op.drop_column('features_daily', 'sharpe_126')
    op.drop_column('features_daily', 'sharpe_63')
    op.drop_column('features_daily', 'sharpe_21')
    op.drop_column('features_daily', 'rs_normalized')
    op.drop_column('features_daily', 'zscore_63')
    op.drop_column('features_daily', 'zscore_21')
    op.drop_column('features_daily', 'skew_63')
    op.drop_column('features_daily', 'skew_21')
    # ### end Alembic commands ###
