"""Rename return columns to period-based

Revision ID: 157e304b613f
Revises: 252e924f5f13
Create Date: 2025-12-25 15:34:26.926055

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '157e304b613f'
down_revision: Union[str, Sequence[str], None] = '252e924f5f13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('features_daily', sa.Column('return_1', sa.Float(), nullable=True))
    op.add_column('features_daily', sa.Column('return_5', sa.Float(), nullable=True))
    op.add_column('features_daily', sa.Column('return_21', sa.Float(), nullable=True))
    op.add_column('features_daily', sa.Column('return_63', sa.Float(), nullable=True))
    op.add_column('features_daily', sa.Column('return_252', sa.Float(), nullable=True))
    op.drop_column('features_daily', 'return_21d')
    op.drop_column('features_daily', 'return_5d')
    op.drop_column('features_daily', 'return_63d')
    op.drop_column('features_daily', 'return_1d')
    op.drop_column('features_daily', 'return_252d')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('features_daily', sa.Column('return_252d', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('features_daily', sa.Column('return_1d', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('features_daily', sa.Column('return_63d', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('features_daily', sa.Column('return_5d', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('features_daily', sa.Column('return_21d', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('features_daily', 'return_252')
    op.drop_column('features_daily', 'return_63')
    op.drop_column('features_daily', 'return_21')
    op.drop_column('features_daily', 'return_5')
    op.drop_column('features_daily', 'return_1')
    # ### end Alembic commands ###
