"""Add asset_time indexes to all tables

Revision ID: 252e924f5f13
Revises: 85bf3a4a553a
Create Date: 2025-12-24 10:24:59.581884

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '252e924f5f13'
down_revision: Union[str, Sequence[str], None] = '85bf3a4a553a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('features_daily_time_idx'), table_name='features_daily')
    op.create_index('idx_features_daily_asset_time', 'features_daily', ['asset_id', sa.literal_column('time DESC')], unique=False)
    op.drop_index(op.f('market_data_5min_time_idx'), table_name='market_data_5min')
    op.create_index('idx_market_data_5min_asset_time', 'market_data_5min', ['asset_id', sa.literal_column('time DESC')], unique=False)
    op.drop_index(op.f('market_data_daily_time_idx'), table_name='market_data_daily')
    op.create_index('idx_market_data_daily_asset_time', 'market_data_daily', ['asset_id', sa.literal_column('time DESC')], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_market_data_daily_asset_time', table_name='market_data_daily')
    op.create_index(op.f('market_data_daily_time_idx'), 'market_data_daily', [sa.literal_column('time DESC')], unique=False)
    op.drop_index('idx_market_data_5min_asset_time', table_name='market_data_5min')
    op.create_index(op.f('market_data_5min_time_idx'), 'market_data_5min', [sa.literal_column('time DESC')], unique=False)
    op.drop_index('idx_features_daily_asset_time', table_name='features_daily')
    op.create_index(op.f('features_daily_time_idx'), 'features_daily', [sa.literal_column('time DESC')], unique=False)
    # ### end Alembic commands ###
