"""Edited Intraday to have multiple timeframes if necessary in the future

Revision ID: 45ecd18b49e7
Revises: d8abc64363e6
Create Date: 2025-12-17 12:12:09.496984

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45ecd18b49e7'
down_revision: Union[str, Sequence[str], None] = 'd8abc64363e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
