"""Add composite PK to features_daily

Revision ID: 49ebe99f4be7
Revises: 9cb0dbdb5103
Create Date: 2025-12-17 19:56:46.469020

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49ebe99f4be7'
down_revision: Union[str, Sequence[str], None] = '9cb0dbdb5103'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
