"""Add meta to models table

Revision ID: 58779f32e13b
Revises: 89742a3ed66c
Create Date: 2025-12-30 18:38:19.332006

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '58779f32e13b'
down_revision: Union[str, Sequence[str], None] = '89742a3ed66c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('models', sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_index(op.f('predictions_time_idx'), table_name='predictions')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('predictions_time_idx'), 'predictions', [sa.literal_column('time DESC')], unique=False)
    op.drop_column('models', 'meta')
    # ### end Alembic commands ###
