"""Add statistical, calendar, and other advanced features

Revision ID: 9255daebd7ff
Revises: 157e304b613f
Create Date: 2025-12-25 16:36:35.098652

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9255daebd7ff'
down_revision: Union[str, Sequence[str], None] = '157e304b613f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('features_daily', sa.Column('adx_14', sa.Float(), nullable=True))
    op.add_column('features_daily', sa.Column('return_126', sa.Float(), nullable=True))
    op.add_column('features_daily', sa.Column('obv', sa.Float(), nullable=True))
    op.add_column('features_daily', sa.Column('mfi_14', sa.Float(), nullable=True))
    op.add_column('features_daily', sa.Column('high_252_pct', sa.Float(), nullable=True))
    op.add_column('features_daily', sa.Column('low_252_pct', sa.Float(), nullable=True))
    op.add_column('features_daily', sa.Column('skew_20', sa.Float(), nullable=True))
    op.add_column('features_daily', sa.Column('skew_60', sa.Float(), nullable=True))
    op.add_column('features_daily', sa.Column('zscore_20', sa.Float(), nullable=True))
    op.add_column('features_daily', sa.Column('zscore_60', sa.Float(), nullable=True))
    op.add_column('features_daily', sa.Column('day_of_week', sa.Integer(), nullable=True))
    op.add_column('features_daily', sa.Column('day_of_month', sa.Integer(), nullable=True))
    op.add_column('features_daily', sa.Column('month_of_year', sa.Integer(), nullable=True))
    op.add_column('features_daily', sa.Column('quarter', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('features_daily', 'quarter')
    op.drop_column('features_daily', 'month_of_year')
    op.drop_column('features_daily', 'day_of_month')
    op.drop_column('features_daily', 'day_of_week')
    op.drop_column('features_daily', 'zscore_60')
    op.drop_column('features_daily', 'zscore_20')
    op.drop_column('features_daily', 'skew_60')
    op.drop_column('features_daily', 'skew_20')
    op.drop_column('features_daily', 'low_252_pct')
    op.drop_column('features_daily', 'high_252_pct')
    op.drop_column('features_daily', 'mfi_14')
    op.drop_column('features_daily', 'obv')
    op.drop_column('features_daily', 'return_126')
    op.drop_column('features_daily', 'adx_14')
    # ### end Alembic commands ###
