"""features_daily table added

Revision ID: 9cb0dbdb5103
Revises: 45ecd18b49e7
Create Date: 2025-12-17 19:47:54.674309

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9cb0dbdb5103'
down_revision: Union[str, Sequence[str], None] = '45ecd18b49e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('features_daily',
    sa.Column('time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('return_1d', sa.Float(), nullable=True),
    sa.Column('return_5d', sa.Float(), nullable=True),
    sa.Column('return_21d', sa.Float(), nullable=True),
    sa.Column('return_63d', sa.Float(), nullable=True),
    sa.Column('return_252d', sa.Float(), nullable=True),
    sa.Column('sma_20', sa.Float(), nullable=True),
    sa.Column('sma_50', sa.Float(), nullable=True),
    sa.Column('sma_200', sa.Float(), nullable=True),
    sa.Column('ema_12', sa.Float(), nullable=True),
    sa.Column('ema_20', sa.Float(), nullable=True),
    sa.Column('ema_26', sa.Float(), nullable=True),
    sa.Column('ema_50', sa.Float(), nullable=True),
    sa.Column('rsi_14', sa.Float(), nullable=True),
    sa.Column('macd', sa.Float(), nullable=True),
    sa.Column('macd_signal', sa.Float(), nullable=True),
    sa.Column('macd_hist', sa.Float(), nullable=True),
    sa.Column('atr_14', sa.Float(), nullable=True),
    sa.Column('atr_14_pct', sa.Float(), nullable=True),
    sa.Column('volume_adv_20', sa.Float(), nullable=True),
    sa.Column('relative_volume', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['asset_metadata.id'], ),
    sa.PrimaryKeyConstraint('time', 'asset_id'),
    sa.UniqueConstraint('time', 'asset_id', name='_daily_features_time_asset_uc')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('features_daily')
    # ### end Alembic commands ###
