"""Add bollinger bands to features_daily

Revision ID: ad882e7a924f
Revises: 49ebe99f4be7
Create Date: 2025-12-19 12:34:07.856838

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad882e7a924f'
down_revision: Union[str, Sequence[str], None] = '49ebe99f4be7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('features_daily', sa.Column('bb_upper_20', sa.Float(), nullable=True))
    op.add_column('features_daily', sa.Column('bb_middle_20', sa.Float(), nullable=True))
    op.add_column('features_daily', sa.Column('bb_lower_20', sa.Float(), nullable=True))
    op.add_column('features_daily', sa.Column('bb_width_20', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('features_daily', 'bb_width_20')
    op.drop_column('features_daily', 'bb_lower_20')
    op.drop_column('features_daily', 'bb_middle_20')
    op.drop_column('features_daily', 'bb_upper_20')
    # ### end Alembic commands ###
