"""Add specific ledger columns

Revision ID: d222678603db
Revises: ad882e7a924f
Create Date: 2025-12-20 10:05:37.148968

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd222678603db'
down_revision: Union[str, Sequence[str], None] = 'ad882e7a924f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('asset_metadata', sa.Column('last_market_data_daily_update', sa.DateTime(timezone=True), nullable=True))
    op.add_column('asset_metadata', sa.Column('last_market_data_5min_update', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('asset_metadata', 'last_market_data_5min_update')
    op.drop_column('asset_metadata', 'last_market_data_daily_update')
    # ### end Alembic commands ###
