"""Add market_context_daily table

Revision ID: d75fe3d0fa2a
Revises: 58779f32e13b
Create Date: 2026-01-09 10:49:42.326241

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d75fe3d0fa2a"
down_revision: Union[str, Sequence[str], None] = "58779f32e13b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "market_context_daily",
        sa.Column("time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("vix_close", sa.Float(), nullable=True),
        sa.Column("vix_pct_change_1d", sa.Float(), nullable=True),
        sa.Column("breadth_pct_above_sma20", sa.Float(), nullable=True),
        sa.Column("breadth_pct_above_sma50", sa.Float(), nullable=True),
        sa.Column("breadth_pct_above_sma200", sa.Float(), nullable=True),
        sa.Column("spy_rsi_14", sa.Float(), nullable=True),
        sa.Column("spy_adx_14", sa.Float(), nullable=True),
        sa.Column("credit_spread_pct_change_5d", sa.Float(), nullable=True),
        sa.Column("tlt_pct_change_21d", sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint("time"),
    )
    op.execute("SELECT create_hypertable('market_context_daily', by_range('time'));")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("market_context_daily")
    # ### end Alembic commands ###
