"""Create initial market data and asset tables

Revision ID: d8abc64363e6
Revises: 
Create Date: 2025-12-16 21:26:53.785627

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8abc64363e6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asset_metadata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('exchange', sa.String(), nullable=True),
    sa.Column('asset_class', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('last_updated', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asset_metadata_id'), 'asset_metadata', ['id'], unique=False)
    op.create_index(op.f('ix_asset_metadata_symbol'), 'asset_metadata', ['symbol'], unique=True)
    op.create_table('market_data_5min',
    sa.Column('time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('open', sa.Float(), nullable=True),
    sa.Column('high', sa.Float(), nullable=True),
    sa.Column('low', sa.Float(), nullable=True),
    sa.Column('close', sa.Float(), nullable=True),
    sa.Column('volume', sa.BigInteger(), nullable=True),
    sa.Column('vwap', sa.Float(), nullable=True),
    sa.Column('trade_count', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['asset_metadata.id'], ),
    sa.PrimaryKeyConstraint('time', 'asset_id'),
    sa.UniqueConstraint('time', 'asset_id', name='_time_asset_id_uc')
    )
    op.create_table('market_data_daily',
    sa.Column('time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('open', sa.Float(), nullable=True),
    sa.Column('high', sa.Float(), nullable=True),
    sa.Column('low', sa.Float(), nullable=True),
    sa.Column('close', sa.Float(), nullable=True),
    sa.Column('volume', sa.BigInteger(), nullable=True),
    sa.Column('vwap', sa.Float(), nullable=True),
    sa.Column('trade_count', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['asset_metadata.id'], ),
    sa.PrimaryKeyConstraint('time', 'asset_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('market_data_daily')
    op.drop_table('market_data_5min')
    op.drop_index(op.f('ix_asset_metadata_symbol'), table_name='asset_metadata')
    op.drop_index(op.f('ix_asset_metadata_id'), table_name='asset_metadata')
    op.drop_table('asset_metadata')
    # ### end Alembic commands ###
