/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/v1/public/market/history/{symbol}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Market History */
    get: operations["get_symbol_history"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/public/market/snapshots": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Market Snapshots
     * @description Returns the latest price, change, and a sparkline trend for a list of symbols.
     *     Optimized for dashboards and watchlists.
     */
    get: operations["get_snapshots_api_v1_public_market_snapshots_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/public/assets": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List or Search Assets */
    get: operations["list_assets_api_v1_public_assets_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/public/assets/{symbol}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Asset Details */
    get: operations["get_asset_detail_api_v1_public_assets__symbol__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/public/discovery/market-leaders": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Market Leaders
     * @description Provides a ranked list of assets based on key daily metrics, designed for market discovery.
     */
    get: operations["get_market_leaders"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/public/system/status": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get System Status
     * @description Checks the freshness of data and overall system health.
     */
    get: operations["get_system_status_api_v1_public_system_status_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/public/intelligence/regime": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Current Market Regime
     * @description Returns the current market regime (Bull/Bear/Risk-On/Off).
     *     Currently implements a Heuristic Logic (v1): SPY Trend + Volatility.
     */
    get: operations["get_market_regime_api_v1_public_intelligence_regime_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Read Root
     * @description A simple health check endpoint.
     */
    get: operations["health_check"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /**
     * AssetDetail
     * @description Complete metadata for a single asset.
     */
    AssetDetail: {
      /** Symbol */
      symbol: string;
      /** Name */
      name?: string | null;
      /** Exchange */
      exchange?: string | null;
      /** Asset Class */
      asset_class: string;
      /** Is Active */
      is_active: boolean;
    };
    /**
     * AssetInfo
     * @description Lightweight asset information, suitable for search results and lists.
     */
    AssetInfo: {
      /** Symbol */
      symbol: string;
      /** Name */
      name?: string | null;
      /** Exchange */
      exchange?: string | null;
    };
    /** CalendarFeatures */
    CalendarFeatures: {
      /** Day Of Week */
      day_of_week?: number | null;
      /** Day Of Month */
      day_of_month?: number | null;
      /** Month Of Year */
      month_of_year?: number | null;
      /** Quarter */
      quarter?: number | null;
    };
    /**
     * Environment
     * @enum {string}
     */
    Environment: "production" | "development" | "staging";
    /**
     * FeatureSet
     * @description A deeply nested object containing all feature families.
     */
    FeatureSet: {
      trend: components["schemas"]["TrendFeatures"];
      momentum: components["schemas"]["MomentumFeatures"];
      volatility: components["schemas"]["VolatilityFeatures"];
      volume: components["schemas"]["VolumeFeatures"];
      structure: components["schemas"]["StructuralFeatures"];
      stats: components["schemas"]["StatFeatures"];
      calendar: components["schemas"]["CalendarFeatures"];
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /**
     * HistoryDataPoint
     * @description The main, combined data point for the history endpoint.
     */
    HistoryDataPoint: {
      /**
       * Time
       * Format: date-time
       */
      time: string;
      /** Open */
      open: number;
      /** High */
      high: number;
      /** Low */
      low: number;
      /** Close */
      close: number;
      /** Volume */
      volume: number;
      features: components["schemas"]["FeatureSet"];
    };
    /**
     * MarketInterval
     * @enum {string}
     */
    MarketInterval: "5m" | "15m" | "30m" | "1h" | "4h" | "1d" | "1w";
    /** MarketRegime */
    MarketRegime: {
      /**
       * Timestamp
       * Format: date-time
       */
      timestamp: string;
      regime: components["schemas"]["RegimeType"];
      risk_signal: components["schemas"]["RiskLevel"];
      /** Trend Score */
      trend_score: number;
      /** Volatility Score */
      volatility_score: number;
      /** Breadth Pct */
      breadth_pct?: number | null;
      /** Market Volatility Avg */
      market_volatility_avg?: number | null;
      /** Summary */
      summary: string;
    };
    /** MarketSnapshot */
    MarketSnapshot: {
      /** Symbol */
      symbol: string;
      /** Price */
      price: number;
      /** Change 1D */
      change_1d?: number | null;
      /** Change 1D Pct */
      change_1d_pct?: number | null;
      /**
       * Last Updated
       * Format: date-time
       */
      last_updated: string;
      /** Sparkline */
      sparkline: number[];
    };
    /** MomentumFeatures */
    MomentumFeatures: {
      /** Rsi 14 */
      rsi_14?: number | null;
      /** Return 1 */
      return_1?: number | null;
      /** Return 5 */
      return_5?: number | null;
      /** Return 21 */
      return_21?: number | null;
      /** Return 63 */
      return_63?: number | null;
      /** Return 126 */
      return_126?: number | null;
      /** Return 252 */
      return_252?: number | null;
    };
    /**
     * RegimeType
     * @enum {string}
     */
    RegimeType: "Bull" | "Bear" | "Sideways";
    /**
     * RiskLevel
     * @enum {string}
     */
    RiskLevel: "Risk On" | "Risk Off" | "Neutral";
    /**
     * ScreenerResult
     * @description Represents a single asset from the Screener/Market Leaders output.
     */
    ScreenerResult: {
      /** Rank */
      rank: number;
      /** Symbol */
      symbol: string;
      /** Name */
      name?: string | null;
      /** Latest Price */
      latest_price: number;
      /** Daily Change Pct */
      daily_change_pct: number;
      /** Relative Volume */
      relative_volume: number | null;
      /** Rsi 14 */
      rsi_14: number | null;
      /** Sma 50 Pct Diff */
      sma_50_pct_diff: number | null;
      /** Atr 14 Pct */
      atr_14_pct: number | null;
    };
    /** StatFeatures */
    StatFeatures: {
      /** Skew 20 */
      skew_20?: number | null;
      /** Skew 60 */
      skew_60?: number | null;
      /** Zscore 20 */
      zscore_20?: number | null;
      /** Zscore 60 */
      zscore_60?: number | null;
    };
    /** StructuralFeatures */
    StructuralFeatures: {
      /** High 252 Pct */
      high_252_pct?: number | null;
      /** Low 252 Pct */
      low_252_pct?: number | null;
    };
    /**
     * SystemHealth
     * @enum {string}
     */
    SystemHealth: "Healthy" | "Degraded" | "Stale" | "Maintenance";
    /** SystemStatus */
    SystemStatus: {
      status: components["schemas"]["SystemHealth"];
      /** Last Daily Update */
      last_daily_update: string | null;
      /** Last Intraday Update */
      last_intraday_update: string | null;
      /** Active Assets */
      active_assets: number;
      environment: components["schemas"]["Environment"];
    };
    /** TrendFeatures */
    TrendFeatures: {
      /** Sma 20 */
      sma_20?: number | null;
      /** Sma 50 */
      sma_50?: number | null;
      /** Sma 200 */
      sma_200?: number | null;
      /** Ema 12 */
      ema_12?: number | null;
      /** Ema 20 */
      ema_20?: number | null;
      /** Ema 26 */
      ema_26?: number | null;
      /** Ema 50 */
      ema_50?: number | null;
      /** Macd */
      macd?: number | null;
      /** Macd Signal */
      macd_signal?: number | null;
      /** Macd Hist */
      macd_hist?: number | null;
      /** Adx 14 */
      adx_14?: number | null;
    };
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
    };
    /** VolatilityFeatures */
    VolatilityFeatures: {
      /** Atr 14 */
      atr_14?: number | null;
      /** Atr 14 Pct */
      atr_14_pct?: number | null;
      /** Bb Upper 20 */
      bb_upper_20?: number | null;
      /** Bb Middle 20 */
      bb_middle_20?: number | null;
      /** Bb Lower 20 */
      bb_lower_20?: number | null;
      /** Bb Width 20 */
      bb_width_20?: number | null;
    };
    /** VolumeFeatures */
    VolumeFeatures: {
      /** Volume Adv 20 */
      volume_adv_20?: number | null;
      /** Relative Volume */
      relative_volume?: number | null;
      /** Obv */
      obv?: number | null;
      /** Mfi 14 */
      mfi_14?: number | null;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  get_symbol_history: {
    parameters: {
      query?: {
        /** @description Aggregation interval */
        interval?: components["schemas"]["MarketInterval"];
        /** @description Start date (UTC) */
        start_date?: string | null;
        /** @description End date (UTC) */
        end_date?: string | null;
        limit?: number;
      };
      header?: never;
      path: {
        symbol: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HistoryDataPoint"][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_snapshots_api_v1_public_market_snapshots_get: {
    parameters: {
      query: {
        /** @description Comma-separated list of symbols (e.g., SPY,BTC,NVDA) */
        symbols: string;
        lookback_days?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["MarketSnapshot"][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_assets_api_v1_public_assets_get: {
    parameters: {
      query?: {
        /** @description Search query for symbol or name */
        q?: string | null;
        limit?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AssetInfo"][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_asset_detail_api_v1_public_assets__symbol__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        symbol: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AssetDetail"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_market_leaders: {
    parameters: {
      query?: {
        /** @description Metric to sort results by. */
        sort_by?:
          | "relative_volume"
          | "rsi_14"
          | "return_1"
          | "volume_adv_20"
          | "atr_14_pct";
        /** @description Sort direction. */
        sort_dir?: "asc" | "desc";
        limit?: number;
        min_price?: number;
        min_avg_volume?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ScreenerResult"][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_system_status_api_v1_public_system_status_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SystemStatus"];
        };
      };
    };
  };
  get_market_regime_api_v1_public_intelligence_regime_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["MarketRegime"];
        };
      };
    };
  };
  health_check: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
    };
  };
}
